version: "3"
services:
  order-beverage-service:
    image: rutvi1212/vending_machine_microservices:final_image_challenge2_578
    hostname: order-beverage-service
    restart: always
    entrypoint: OrderBeverageService

  weather-service:
    image: rutvi1212/vending_machine_microservices:final_image_challenge2_578
    hostname: weather-service
    restart: always
    entrypoint: WeatherService
    
  beverage-preference-service:
    image: rutvi1212/vending_machine_microservices:final_image_challenge2_578
    hostname: beverage-preference-service
    restart: always
    entrypoint: BeveragePreferenceService
    
  nginx-thrift:
    image: yg397/openresty-thrift:xenial
    hostname: nginx-thrift
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./nginx_reverse_proxy/lua-scripts:/usr/local/openresty/nginx/lua-scripts
      - ./nginx_reverse_proxy/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./gen-lua:/gen-lua
      

